<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ActivePatternTest.fs" />
    <Compile Include="BasicsTest.fs" />
    <Compile Include="CharMatcherTest.fs" />
    <Compile Include="CollectionValidationTest.fs" />
    <Compile Include="ISO10646CollectionTest.fs" />
    <Compile Include="ReadCharacterTest.fs" />
    <Compile Include="ReadGraphemeClusterTest.fs" />
    <Compile Include="RepertoireTest.fs" />
    <Compile Include="ThreeValuedBooleanTest.fs" />
    <Compile Include="ValidationTest.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.9.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CREPDL\CREPDL.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.303" />
  </ItemGroup>

</Project>
