<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
    <EmbeddedResource Include="DerivedAge.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EPUBConsoleApplication\EPUBConsoleApplication.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.201" />
  </ItemGroup>
</Project>